import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Killian',
      email: 'admin@zifast.store',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Mandla',
      email: 'mandla@zifast.store',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'ZiFast Vegetable Box',
      slug: 'zifast-vegetable-box',
      category: 'Vegetables',
      image: '/images/p1.jpg',
      price: 12,
      countInStock: 10,
      brand: 'N/A',
      rating: 4.5,
      numReviews: 10,
      description:
        'Potatoes, Tomatoes, Onion, Carrot, Cabbage, Lettuce, Brocolli, Cauliflower, Sweet Potato, Cucumber, Beetroot',
    },
    {
      //_id: '2',
      name: 'Brocolli',
      slug: 'brocolli',
      category: 'Vegetables',
      image: '/images/p2.jpg',
      price: 2,
      countInStock: 5,
      brand: 'N/A',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '3',
      name: 'Butternut',
      slug: 'butternut',
      category: 'Vegetables',
      image: '/images/p3.jpg',
      price: 1.5,
      countInStock: 7,
      brand: 'N/A',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      //_id: '4',
      name: 'Carrots',
      slug: 'carrots',
      category: 'Vegetables',
      image: '/images/p4.jpg',
      price: 1.5,
      countInStock: 7,
      brand: 'N/A',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id: '5',
      name: 'Cucumber',
      slug: 'cucumber',
      category: 'Vegetables',
      image: '/images/p5.jpg',
      price: 2,
      countInStock: 11,
      brand: 'N/A',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '6',
      name: 'Cabbage',
      slug: 'cabbage',
      category: 'Vegetables',
      image: '/images/p6.jpg',
      price: 0.5,
      countInStock: 4,
      brand: 'N/A',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      //_id: '7',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p7.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      //_id: '8',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p8.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '9',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p9.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id: '10',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p10.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
